variable "name" {
  description = "name to be used to scope all resources under"
  default     = "roz"
}

variable "public_key" {
  description = "public key to use for ssh access to bastion"
}

variable "telegram_token" {
  description = "telegram token generated by BotFather after calling /newbot"
}

variable "telegram_user" {
  description = "telegram user to send messages to"
}

module "roz" {
  source         = "./modules"
  name           = "${var.name}"
  public_key     = "${var.public_key}"
  telegram_token = "${var.telegram_token}"
  telegram_user  = "${var.telegram_user}"
}
