// set up the AWS provider
provider "aws" {
  region = "us-east-1"
}

// used to make calls to telegram through the api
variable "telegram_token" {
  description = "telegram token generated by BotFather after calling /newbot"
}

// the user or chatid that all communications will go to
variable "telegram_user" {
  description = "telegram user to send messages to"
}

// create a random pet based id for pseudo-secret path
resource "random_pet" "roz" {}

// create a local name based upon the pet
locals {
  name = "roz-${random_pet.roz.id}"
}

