provider "aws" {
  region = "us-east-1"
}

variable "name" {
  description = "name to be used to scope all resources under"
  default = "roz"
}

variable "telegram_token" {
  description = "telegram token generated by BotFather after calling /newbot"
}

variable "telegram_user" {
  description = "telegram user to send messages to"
}

